name: EasyTP
main: Rushil13579\EasyTP\EasyTP
api: 3.0.0
version: 1.3.0

commands:
  tpa:
    description: Send a tp request to a player!
    aliases: [tpask]
  tpahere:
    description: Send a tphere request to a player!
    aliases: [tph]
  tpaccept:
    description: Accept a tp request from a player!
    aliases: [tpyes, tpok]
  tpdeny:
    description: Deny a tp request from a player!
    aliases: [tpno, tpdecline]
  tpwithdraw:
    description: Allows you to withdraw your latest tp request!
  tpopen:
    description: Turn on your tp requests!
  tpclose:
    description: Turn off your tp requests!
  tpblock:
    description: Block a player from sending a tp request!
  tpunblock:
    description: Unblock a player from sending a tp request!
  tphere:
    description: Tp a player to your position!
  tpall:
    description: Tp all online players to your position!
  tpworld:
    descritpion: Tp to a world!
    aliases: [tpw]

permissions:
  easytp.command.*:
    description: Allows access to all EasyTP commands!
    children:
      easytp.command.tphere:
        description: Allows a player to use tphere!
      easytp.command.tpall:
        description: Allows a player to use tpall!
      easytp.command.tpworld:
        description: Allows a player to teleport to a world!
